name: Hello World
on:
  push:
    branches:
      - setup
jobs:
  say-hello:
    runs-on: ubuntu-latest
    container:
      volumes:
        - /mnt/user/appdata/KamiTasks:/KamiTasks
    steps:
      - name: Send Discord Start Notification
        # if: false
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "content": "Wave Link Build started on Gitea",
              "embeds": [
                {
                  "title": "Wave Link Build Started",
                  "description": "Wave Link Build process **started** on Gitea",
                  "color": 3447003,
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "'${{ github.repository }}'",
                      "inline": true
                    },
                    {
                      "name": "Branch",
                      "value": "'${{ github.ref }}'",
                      "inline": true
                    },
                    {
                      "name": "Commit",
                      "value": "'${{ github.sha }}'",
                      "inline": true
                    }
                  ],
                  "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
                }
              ]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - uses: actions/checkout@v4
    
      # Install .NET 9 SDK
      - name: Setup .NET 10
        # if: false
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      # Restore dependencies
      - name: Restore dependencies
        # if: false
        run: dotnet restore
      
      # Build the solution
      - name: Build
        # if: false
        run: dotnet build --no-restore
      
      # Publish the x64
      - name: Publish win x64
        # if: false
        run: dotnet publish WaveLink.Plugin/WaveLink.Plugin.csproj -c Release -o ./publish/win_x64/WaveLinkPlugin -r win-x64 --self-contained

      - name: Publish mac x64
        # if: false
        run: dotnet publish WaveLink.Plugin/WaveLink.Plugin.csproj -c Release -o ./publish/osx_x64/WaveLinkPlugin -r osx-x64 --self-contained
        
      - name: Publish mac arm
        # if: false
        run: dotnet publish WaveLink.Plugin/WaveLink.Plugin.csproj -c Release -o ./publish/osx_arm64/WaveLinkPlugin -r osx-arm64 --self-contained
      - name: Compute tag from entry
        id: tag
        run: |
          VERSION=$(jq -r '.version' WaveLink.Plugin/entry.tp)
          PATCH=$((VERSION % 10))
          MINOR=$(((VERSION / 10) % 10))
          MAJOR=$((VERSION / 100))

          TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git tag ${{ steps.tag.outputs.TAG }}
          git push origin tag ${{ steps.tag.outputs.TAG }}

      - name: Show tag
        run: |
          echo "TAG=${{ steps.tag.outputs.TAG }}"
          git tag --list

      - name: Zip win x64 (named folder)
        run: |    
          cd publish/win_x64
          zip -r ../../WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_win_x64.tpp WaveLinkPlugin -x "*.pdb" "entry2.tp" "start_plugin-2.sh"
          mv WaveLinkPlugin/entry.tp WaveLinkPlugin/entry1.tp
          mv WaveLinkPlugin/appsettings.json WaveLinkPlugin/appsettings1.json
          mv WaveLinkPlugin/entry2.tp WaveLinkPlugin/entry.tp
          mv WaveLinkPlugin/appsettings2.json WaveLinkPlugin/appsettings.json
          mv WaveLinkPlugin/WaveLink.Plugin.exe WaveLinkPlugin/WaveLink.Plugin-2.exe
          mv WaveLinkPlugin WaveLinkPlugin2
          zip -r ../../WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_win_x64_multi.tpp WaveLinkPlugin2 -x "*.pdb" "entry1.tp" "start_plugin.sh"

      - name: Zip osx x64
        run: |
          cd publish/osx_x64
          zip -r ../../WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_osx_x64.tpp WaveLinkPlugin -x "*.pdb" "entry2.tp" "start_plugin-2.sh"
          mv WaveLinkPlugin/entry.tp WaveLinkPlugin/entry1.tp
          mv WaveLinkPlugin/appsettings.json WaveLinkPlugin/appsettings1.json
          mv WaveLinkPlugin/entry2.tp WaveLinkPlugin/entry.tp
          mv WaveLinkPlugin/appsettings2.json WaveLinkPlugin/appsettings.json
          mv WaveLinkPlugin/WaveLink.Plugin WaveLinkPlugin/WaveLink.Plugin-2
          mv WaveLinkPlugin WaveLinkPlugin2
          zip -r ../../WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_osx_x64_multi.tpp WaveLinkPlugin2 -x "*.pdb" "entry1.tp" "start_plugin.sh"

      - name: Zip osx arm64
        run: |
          cd publish/osx_arm64
          zip -r ../../WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_osx_arm64.tpp WaveLinkPlugin -x "*.pdb" "entry2.tp" "start_plugin-2.sh"
          mv WaveLinkPlugin/entry.tp WaveLinkPlugin/entry1.tp
          mv WaveLinkPlugin/appsettings.json WaveLinkPlugin/appsettings1.json
          mv WaveLinkPlugin/entry2.tp WaveLinkPlugin/entry.tp
          mv WaveLinkPlugin/appsettings2.json WaveLinkPlugin/appsettings.json
          mv WaveLinkPlugin/WaveLink.Plugin WaveLinkPlugin/WaveLink.Plugin-2
          mv WaveLinkPlugin WaveLinkPlugin2
          zip -r ../../WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_osx_arm64_multi.tpp WaveLinkPlugin2 -x "*.pdb" "entry1.tp" "start_plugin.sh"

     

      # create the release
      - name: Create Gitea Release
        uses: akkuman/gitea-release-action@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          name: Wave Link Plugin ${{ steps.tag.outputs.TAG }}
          prerelease: true
          token: ${{ secrets.GITEA_TOKEN }}
          files: |
            WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_win_x64.tpp
            WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_osx_x64.tpp
            WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_osx_arm64.tpp
            WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_win_x64_multi.tpp
            WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_osx_x64_multi.tpp
            WaveLinkPlugin_${{ steps.tag.outputs.TAG }}_osx_arm64_multi.tpp

      - name: Handle Build Failure
        if: failure()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "content": "Build failed on Gitea",
              "embeds": [
                {
                  "title": "Build failed",
                  "description": "Build process **failed** on Gitea",
                  "color": 3447003,
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "'${{ github.repository }}'",
                      "inline": true
                    },
                    {
                      "name": "Branch",
                      "value": "'${{ github.ref }}'",
                      "inline": true
                    },
                    {
                      "name": "Commit",
                      "value": "'${{ github.sha }}'",
                      "inline": true
                    }
                  ],
                  "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
                }
              ]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord End Notification
        if: success()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "content": "Wave Link Build finished on Gitea",
              "embeds": [
                {
                  "title": "Wave Link Build finished",
                  "description": "Build process **finished** on Gitea",
                  "color": 3447003,
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "'${{ github.repository }}'",
                      "inline": true
                    },
                    {
                      "name": "Branch",
                      "value": "'${{ github.ref }}'",
                      "inline": true
                    },
                    {
                      "name": "Commit",
                      "value": "'${{ github.sha }}'",
                      "inline": true
                    }
                  ],
                  "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
                }
              ]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}